############################公共表#################################
#服务端口
server:
  port: 8098
#服务名
spring:
  main:
    allow-bean-definition-overriding: true
  #shardingsphere相关配置
  shardingsphere:
    datasource:
      names: m1,m2   #配置库的名字，随意
      m1:   #配置目前m1库的数据源信息
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.60.165:3306/user_db?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
        username: admini
        password: 123456
      m2:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.60.206:3306/user_db?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
        username: admini
        password: 123456
    sharding:
      broadcast‐tables: t_dict  #公共表
      tables:
        t_dict:
          key-generator:
            column: dict_id
            type: SNOWFLAKE
    props:
      sql:
        show: true   #打印sql
 
 
#日志打印
logging:
  level:
    root: info
    org.springframework.web: info
    com.zzg.mapper: debug
    druid.sql: debug